CREATE DATABASE TRACKER;
CREATE TABLE TRACKER.BUG (
  ID          INT,
  NAME        VARCHAR(32),
  DESCRIPTION VARCHAR(100)
);
CREATE TABLE TRACKER.employee (
  ID       INT PRIMARY KEY AUTO_INCREMENT,
  name     VARCHAR(32),
  surname  VARCHAR(32),
  mail     VARCHAR(32),
  position VARCHAR(32),
  password VARCHAR(32)
);
CREATE TABLE TRACKER.project (
  ID         INT,
  name       VARCHAR(32),
  description VARCHAR(32),
  manager   VARCHAR(32)
);
CREATE TABLE TRACKER.ISSUE (
  ID          INT PRIMARY KEY AUTO_INCREMENT,
  SUMMARY        VARCHAR(32),
  DESCRIPTION VARCHAR(100),
  STATUS VARCHAR(16),
  TYPE VARCHAR(16),
  PRIORITY VARCHAR(16),
  PROJECT VARCHAR(32),
  BUILD_FOUND VARCHAR(16),
  ASSIGNEE VARCHAR(100)
);
CREATE TABLE TRACKER.BILD (
  ID          INT PRIMARY KEY AUTO_INCREMENT,
  VERSION        VARCHAR(32),
  PROJECT_ID INT
)